### PR TITLE
TOOLS-2540 eng.git buildimage copy of imgadm needs updating

### PR DESCRIPTION
**Pull request by bahamat**
I've finally figured out enough about how all of this works to be able to actually test this.

To test, I created a prototype jenkins-agent-21.4.0 instance with the current eng.git (which has broken imgadm), and updated things manually until I got it all working. With these changes, I'm able to use the jenkins-agent to successfully build a triton-origin-21.4.0 image (see companion commit joyent/triton-origin-image#8).

Summary of changes:

* Update README to list additional differences
* Update package.json to closer match versions in smartos-live.
  * sdc-clients needs to be newer than smartos-live to get channel support, but not so new that dsapi is removed.
  * Eventually platform imgadm should be updated to match sdc-imgapi-cli, then this one can go forward as well
* The interpreter line has been changed to `/opt/tools/bin/node` instead of attempting to use the platform node (which will not work). This allows independent testing/usage of this embedded imgadm

### CODE REVIEW

**Comment by danmcd** [comment]
1. Copy those test notes into the Jira ticket.
2. Please file an OS bug for the necessary imgadm update(s).

Do those and I approve.

**Comment by bahamat** [comment]
Done.

**Comment by danmcd** [comment]
What's the OS-bug?

**Review by danmcd — APPROVED** [review]
Thanks for the testing notes, please file the OS bug I requested.

**Comment by bahamat** [comment]
I looked through jira and found an existing one: [OS-7842](https://smartos.org/bugview/OS-7842)

**Pull request merged**
